### ISSUE TITLE
Animate All Page/State Transitions

### ISSUE THREAD

**Issue by iamshawnrice** [iamshawnrice/iamshawnrice#10]
## Order of Operations:
1. Click Internal Navigation Link
2. Content of current page/view vanishes in a 'dramatic fashion'.
3. Contents of new page/view enters in a 'dramatic fashion'.
## Ideas for 'dramatic fashion':
- Each DOM node has random translation applied 30 px and fades out
- Each DOM node fades in consecutively
- Title of each page/view [shuffles in](http://demo.tutorialzine.com/2011/09/shuffle-letters-effect-jquery/) and the content fades/scales/slides in

_OR_ perhaps the old content doesn't disappear, but is covered or removed by a [geometrical transformation](http://tympanus.net/Development/PageTransitions/)
- The old content is covered by the new content with a 'background' pane like a card.
- The old content rotates like the face of a cube (we could set background colors for certain 'faces')
# Tasks:
- [x] Move 'paplow' element into footer & affix footer to bottom of viewport
- [x] Restyle footer on mobile-sized screens

**Comment by iamshawnrice** [comment]
# Tasks:
- [ ] Move 'paplow' element into footer & affix footer to bottom of viewport
- [ ] Experiment with animating the page elements in/out
- [ ] Experiment with animating the 'paplow' element to/from the footer during http requests
- [ ] Finalize all state change related page animations
- [ ] Restyle footer on mobile-sized screens
